const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto').webcrypto,path=require('node:path');
const root=path.resolve(__dirname,'..');
function fixture(){const data=new Map();let failKey='';const localStorage={getItem:k=>data.get(k)??null,setItem(k,v){if(k===failKey){failKey='';throw Error('quota test');}data.set(k,String(v));},removeItem:k=>data.delete(k)};const set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));const ctx={localStorage,navigator:{locks:{request:async(k,f)=>f()}},crypto,TextEncoder,TextDecoder,Uint8Array,btoa,atob,Event,CustomEvent:class{},setTimeout,clearTimeout,Intl,console,addEventListener(){},dispatchEvent(){}};ctx.window=ctx;vm.runInNewContext(fs.readFileSync(path.join(root,'self-pos-core.js'),'utf8'),ctx);vm.runInNewContext(fs.readFileSync(path.join(root,'vendor/fflate-0.8.2.min.js'),'utf8'),ctx);vm.runInNewContext(fs.readFileSync(path.join(root,'self-pos-runtime.js'),'utf8'),ctx);set('salon_settings',{shopID:'test',syncToken:'test-key',commissionRates:{剪髮:50,產品:10},deductCostBeforeCommission:true});set('salon_services',[{id:'cut',name:'剪髮',price:600,cost:20,isProduct:false,category:'剪髮',stock:null},{id:'p',name:'洗髮精',price:800,cost:400,isProduct:true,category:'產品',stock:3}]);set('salon_stylists',[{id:'s1',name:'甲',useGlobalCommission:true},{id:'s2',name:'乙',useGlobalCommission:false,commissionRate:40}]);set('salon_customers',[{id:'c',name:'顧客',visits:2,totalSpend:1000}]);for(const k of ['salon_transactions','salon_pending_orders','salon_inventory_logs','salon_expenses'])set(k,[]);const store=ctx.SalonStore;return {ctx,set,store,data,fail:k=>failKey=k,input:(id='one')=>({id,items:[{...store.all().services[0],cartId:'line1',stylistId:'s1'},{...store.all().services[1],cartId:'line2',stylistId:'s1'}],stylistId:'s1',customerId:'c',date:'2026-10-01T07:30',paymentMethod:'現金'})};}
(async()=>{
 let f=fixture(),S=f.store,o=await S.checkout(f.input());assert.equal(o.total,1400);assert.equal(S.all().services[1].stock,2);assert.equal(S.all().customers[0].totalSpend,2400);await S.checkout(f.input());assert.equal(S.all().transactions.length,1);assert.equal(S.all().customers[0].visits,3);console.log('PASS atomic checkout and same-draft retry are idempotent');
 await S.reviseOrder({...o,mainStylistId:'s2',items:[o.items[0]]});assert.equal(S.all().services[1].stock,3);assert.equal(S.all().transactions[0].items[0].stylistId,'s2');assert.equal(S.all().transactions[0].items[0].commissionRate,40);assert.equal(S.all().customers[0].totalSpend,1600);await S.reviseOrder(S.all().transactions[0],true);assert.equal(S.all().customers[0].totalSpend,1000);assert.equal(S.all().customers[0].visits,2);console.log('PASS revise/delete synchronizes inventory, customer totals and stylist');
 f=fixture();S=f.store;f.set('salon_services',S.all().services.map(s=>({...s,stock:0})));await assert.rejects(S.checkout(f.input()),/庫存不足/);assert.equal(S.all().transactions.length,0);assert.equal(S.all().customers[0].visits,2);console.log('PASS rejected checkout leaves data unchanged');
 f=fixture();S=f.store;f.fail('salon_services');await assert.rejects(S.checkout(f.input()),/儲存未完成/);assert.ok(f.data.has(f.ctx.AetherPosBridge.PREFIX+'journal'));await S.checkout(f.input());assert.equal(S.all().transactions.length,1);assert.equal(S.all().services[1].stock,2);assert.equal(S.all().customers[0].visits,3);console.log('PASS interrupted commit recovers exactly once');
 f=fixture();S=f.store;await S.inventory({id:'p',action:'internal',qty:1,internalUseType:'designer',staffId:'s1'});assert.equal(S.all().services[1].stock,2);assert.equal(S.all().expenses.length,1);await assert.rejects(S.inventory({id:'p',action:'adjust',adjustType:'dec',qty:3}),/庫存不足/);assert.equal(S.all().services[1].stock,2);await assert.rejects(S.inventory({id:'p',action:'restock',qty:1.5,cost:20}),/整數/);console.log('PASS inventory validation and linked expense');
 const pending=await S.savePending({cart:f.input().items,draftId:'draft-a'},'waiting');S.draftSave({cart:f.input().items,pendingId:pending.id});assert.equal(S.backupPayload().pendingOrders.length,1);assert.equal(S.backupPayload().draft.pendingId,pending.id);await S.checkout({...f.input(),pendingId:pending.id});assert.equal(S.all().pendingOrders.length,0);assert.equal(S.draftRead(),null);console.log('PASS complete backup and checkout removes only completed pending order');
 assert.equal(S.day('2026-09-30T23:30:00Z'),'2026-10-01');assert.equal(S.itemCost({cost:300},1800),300);assert.equal(S.itemCost({cost:20,costMode:'percent'},1000),200);await assert.rejects(S.restore({transactions:[]}),/完整/);console.log('PASS Taiwan date, explicit cost units and incomplete backup rejection');
 f=fixture();S=f.store;let remote=null,patches=0;f.ctx.fetch=async(url,opt)=>{if(opt?.method==='PATCH'){patches++;assert.ok(url.includes('currentDocument.'));remote={...JSON.parse(opt.body),updateTime:'2026-10-03T01:00:00Z'};return {ok:true,status:200,json:async()=>remote};}return {ok:!!remote,status:remote?200:404,json:async()=>remote};};await S.cloudBackup(S.all().settings,true);assert.equal(patches,1);assert.equal(S.cloudSnapshot().state,'saved');remote.updateTime='2026-10-03T02:00:00Z';await assert.rejects(S.cloudBackup(S.all().settings,true),/其他裝置/);assert.equal(patches,1);assert.equal(S.all().transactions.length,0);console.log('PASS cloud readback confirmation and concurrent-device overwrite protection');
 // Exercise real compression on data larger than Firestore's entire document limit.
 f=fixture();S=f.store;remote=null;patches=0;let corruptRead=false;
 f.ctx.fetch=async(url,opt)=>{if(opt?.method==='PATCH'){patches++;remote={...JSON.parse(opt.body),updateTime:'revision-'+patches};return {ok:true,status:200,json:async()=>remote};}return {ok:!!remote,status:remote?200:404,json:async()=>corruptRead?{...remote,fields:{content:{stringValue:'{}'}}}:remote};};
 const large=Array.from({length:8000},(_,i)=>({id:'order-'+i,customerId:'c',date:'2026-10-03T10:00',items:[{name:'剪髮／染髮／護髮 ✂️',stylistId:'s1',price:1800}],total:1800,note:'測試完整備份，不得遺漏掛單與顧客資料'}));f.set('salon_transactions',large);S.draftSave({cart:[{name:'尚未結帳'}]});
 const expected=JSON.stringify(S.all().transactions);assert.ok(new TextEncoder().encode(JSON.stringify(S.backupPayload())).length>1048576);
 await S.cloudBackup(S.all().settings,true);assert.equal(patches,1);assert.equal(S.cloudSnapshot().state,'saved');const envelope=JSON.parse(remote.fields.content.stringValue);assert.equal(envelope.format,'salon-pos-gzip-v1');assert.ok(remote.fields.content.stringValue.length<900000);
 let downloaded=await S.cloudDownload(S.all().settings);assert.equal(JSON.stringify(downloaded.transactions),expected);assert.equal(downloaded.draft.cart[0].name,'尚未結帳');console.log('PASS >1 MiB multilingual backup compresses, reads back and restores every record');
 // Modern native compression interoperates with the bundled legacy-browser decoder.
 f.ctx.CompressionStream=CompressionStream;f.ctx.Blob=Blob;f.ctx.Response=Response;await S.cloudBackup(S.all().settings,true);downloaded=await S.cloudDownload(S.all().settings);assert.equal(JSON.stringify(downloaded.transactions),expected);console.log('PASS native and fallback gzip produce readable backups');
 remote.fields.content.stringValue=JSON.stringify({...JSON.parse(remote.fields.content.stringValue),sha256:'0'.repeat(64)});await assert.rejects(S.cloudDownload(S.all().settings),/完整性/);assert.equal(JSON.stringify(S.all().transactions),expected);console.log('PASS corrupt compressed backup never changes local orders');
 corruptRead=true;await assert.rejects(S.cloudBackup(S.all().settings,true),/讀回/);assert.equal(S.cloudSnapshot().state,'error');console.log('PASS successful PATCH alone cannot report backup success');await assert.rejects(S.cloudBackup(S.all().settings),/手動/);corruptRead=false;await S.cloudBackup(S.all().settings,true);assert.equal(S.cloudSnapshot().state,'saved');console.log('PASS failed readback requires manual retry and permits safe recovery');
 // Incompressible oversized backup must stop before writing, preserving prior remote data.
 f=fixture();S=f.store;patches=0;f.ctx.fetch=async(url,opt)=>{if(opt?.method==='PATCH')patches++;return {ok:false,status:404,json:async()=>({})};};const random=require('node:crypto').randomBytes(1000000).toString('base64');f.set('salon_transactions',[{id:'random',note:random}]);await assert.rejects(S.cloudBackup(S.all().settings,true),/壓縮後仍有/);assert.equal(patches,0);assert.equal(S.all().transactions[0].note,random);console.log('PASS oversize compressed backup preserves local data without cloud write');
})().catch(e=>{console.error(e);process.exitCode=1});
