const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom'),crypto=require('node:crypto').webcrypto;
const root=path.resolve(__dirname,'..'),delay=()=>new Promise(r=>setTimeout(r,25));
async function fixture(seed={}){const dom=new JSDOM('<!DOCTYPE html><div id="root"></div>',{url:'https://example.test/pos222222/',runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window;w.alert=()=>{};w.confirm=()=>true;w.prompt=()=>'';w.TextEncoder=TextEncoder;w.crypto.randomUUID=()=>crypto.randomUUID();w.navigator.locks={request:async(k,f)=>f()};w.fetch=()=>Promise.reject(Error('No cloud access in UI tests'));for(const [k,v]of Object.entries(seed))w.localStorage.setItem(k,JSON.stringify(v));const errors=[];w.addEventListener('error',e=>{errors.push(e.error);e.preventDefault();});for(const file of ['vendor/react.production.min.js','vendor/react-dom.production.min.js','self-pos-core.js','self-pos-runtime.js','app.js'])w.eval(fs.readFileSync(path.join(root,file),'utf8'));await delay();const button=text=>[...w.document.querySelectorAll('button')].find(b=>b.textContent.trim()===text);const click=async text=>{const b=button(text);assert.ok(b,'Button '+text);assert.ok(!b.disabled,'Enabled '+text);b.click();await delay();};return{dom,w,errors,button,click,close:()=>dom.window.close()};}
(async()=>{
 let f=await fixture(),w=f.w;
 await f.click('剪髮精緻剪髮$600');let selectors=w.document.querySelectorAll('select');selectors[1].value='st3';selectors[1].dispatchEvent(new w.Event('change',{bubbles:true}));await delay();assert.equal(w.SalonStore.draftRead().cart.length,1);assert.equal(w.SalonStore.draftRead().cart[0].stylistId,'st3');assert.ok(f.button('結帳收款'));console.log('PASS changing stylist/toast keeps cart and selection');
 await f.click('顧客資料');await f.click('收銀開單');assert.equal(w.SalonStore.draftRead().cart.length,1);assert.ok(w.document.body.textContent.includes('$600'));console.log('PASS navigation restores unfinished draft');
 await f.click('挂單');assert.equal(w.SalonStore.all().pendingOrders.length,1);assert.equal(w.SalonStore.draftRead(),null);await f.click('取單 (1)');await f.click('取單');assert.equal(w.SalonStore.draftRead().cart.length,1);assert.equal(w.SalonStore.all().pendingOrders.length,1);console.log('PASS taking a pending order retains durable original until checkout');
 await f.click('結帳收款');const cash=f.button('現金');cash.click();cash.click();await delay();assert.equal(w.SalonStore.all().transactions.length,1);assert.equal(w.SalonStore.all().pendingOrders.length,0);assert.equal(w.SalonStore.all().transactions[0].mainStylistId,'st3');console.log('PASS checkout double tap creates only one complete order');
 await f.click('顧客資料');await f.click('新增顧客');await f.click('儲存資料');assert.equal(w.SalonStore.all().customers.length,0);assert.ok(w.document.body.textContent.includes('請填寫顧客姓名'));assert.equal(f.errors.length,0);console.log('PASS blank customer rejected without blank screen');f.close();
 f=await fixture({salon_customers:[{id:'c',name:'測試客人',phone:'0900000000',visits:0,totalSpend:0}],salon_transactions:[],salon_expenses:[{id:'advance',date:'2026-10-03',type:'員工借支',staffId:'st1',amount:1000}]});w=f.w;
 const search=w.document.querySelector('input');Object.getOwnPropertyDescriptor(w.HTMLInputElement.prototype,'value').set.call(search,'測試');search.dispatchEvent(new w.Event('input',{bubbles:true}));await delay();const item=[...w.document.querySelectorAll('#pos-member-dropdown > div')][0];assert.ok(item,'member result');item.click();await delay();assert.equal(f.errors.length,0);assert.equal(w.SalonStore.draftRead().selectedCustomer.id,'c');console.log('PASS member selection has no undefined-variable error');
 await f.click('營運報表');await f.click('人員薪資');assert.ok(w.document.body.textContent.includes('1,000'));console.log('PASS newly recorded staffId advance is included in salary report');
 await f.click('系統設定');assert.ok(w.document.body.textContent.includes('外觀與操作設定'));await f.click('新增項目');const check=[...w.document.querySelectorAll('input[type="checkbox"]')].find(e=>e.parentElement.textContent.includes('啟用庫存管理'));check.click();await delay();assert.ok(w.document.body.textContent.includes('每件商品成本（元）'));assert.equal(f.errors.length,0);console.log('PASS settings/modal remain stable and product cost unit is explicit');f.close();
})().catch(e=>{console.error(e);process.exitCode=1});
