const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto').webcrypto,path=require('node:path');
const root=path.resolve(__dirname,'..');
function fixture(){const data=new Map();let failKey='',quota=Infinity;const localStorage={getItem:k=>data.get(k)??null,setItem(k,v){if(k===failKey){failKey='';throw Error('quota test');}const total=[...data].reduce((n,[key,value])=>n+(key===k?0:key.length+value.length),0)+k.length+String(v).length;if(total>quota){const e=Error('The quota has been exceeded.');e.name='QuotaExceededError';throw e;}data.set(k,String(v));},removeItem:k=>data.delete(k)};const set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));const ctx={localStorage,navigator:{locks:{request:async(k,f)=>f()}},crypto,TextEncoder,TextDecoder,Uint8Array,btoa,atob,Event,CustomEvent:class{},setTimeout,clearTimeout,Intl,console,addEventListener(){},dispatchEvent(){}};ctx.window=ctx;for(const file of ['vendor/fflate-0.8.2.min.js','self-pos-storage.js','self-pos-core.js'])vm.runInNewContext(fs.readFileSync(path.join(root,file),'utf8'),ctx);vm.runInNewContext(fs.readFileSync(path.join(root,'self-pos-runtime.js'),'utf8'),ctx);set('salon_settings',{shopID:'test',syncToken:'test-key',commissionRates:{剪髮:50,產品:10},deductCostBeforeCommission:true});set('salon_services',[{id:'cut',name:'剪髮',price:600,cost:20,isProduct:false,category:'剪髮',stock:null},{id:'p',name:'洗髮精',price:800,cost:400,isProduct:true,category:'產品',stock:3}]);set('salon_stylists',[{id:'s1',name:'甲',useGlobalCommission:true},{id:'s2',name:'乙',useGlobalCommission:false,commissionRate:40}]);set('salon_customers',[{id:'c',name:'顧客',visits:2,totalSpend:1000}]);for(const k of ['salon_transactions','salon_pending_orders','salon_inventory_logs','salon_expenses'])set(k,[]);const store=ctx.SalonStore;return {ctx,set,store,data,fail:k=>failKey=k,quota:n=>quota=n,input:(id='one')=>({id,items:[{...store.all().services[0],cartId:'line1',stylistId:'s1'},{...store.all().services[1],cartId:'line2',stylistId:'s1'}],stylistId:'s1',customerId:'c',date:'2026-10-01T07:30',paymentMethod:'現金'})};}
(async()=>{
 let f=fixture(),S=f.store,o=await S.checkout(f.input());assert.equal(o.total,1400);assert.equal(S.all().services[1].stock,2);assert.equal(S.all().customers[0].totalSpend,2400);await S.checkout(f.input());assert.equal(S.all().transactions.length,1);assert.equal(S.all().customers[0].visits,3);console.log('PASS atomic checkout and same-draft retry are idempotent');
 await S.reviseOrder({...o,mainStylistId:'s2',items:[o.items[0]]});assert.equal(S.all().services[1].stock,3);assert.equal(S.all().transactions[0].items[0].stylistId,'s2');assert.equal(S.all().transactions[0].items[0].commissionRate,40);assert.equal(S.all().customers[0].totalSpend,1600);await S.reviseOrder(S.all().transactions[0],true);assert.equal(S.all().customers[0].totalSpend,1000);assert.equal(S.all().customers[0].visits,2);console.log('PASS revise/delete synchronizes inventory, customer totals and stylist');
 f=fixture();S=f.store;f.set('salon_services',S.all().services.map(s=>({...s,stock:0})));await assert.rejects(S.checkout(f.input()),/庫存不足/);assert.equal(S.all().transactions.length,0);assert.equal(S.all().customers[0].visits,2);console.log('PASS rejected checkout leaves data unchanged');
 f=fixture();S=f.store;f.fail('salon_services');await assert.rejects(S.checkout(f.input()),/儲存未完成/);assert.ok(f.data.has(f.ctx.AetherPosBridge.PREFIX+'journal'));await S.checkout(f.input());assert.equal(S.all().transactions.length,1);assert.equal(S.all().services[1].stock,2);assert.equal(S.all().customers[0].visits,3);console.log('PASS interrupted commit recovers exactly once');
 f=fixture();S=f.store;await S.inventory({id:'p',action:'internal',qty:1,internalUseType:'designer',staffId:'s1'});assert.equal(S.all().services[1].stock,2);assert.equal(S.all().expenses.length,1);await assert.rejects(S.inventory({id:'p',action:'adjust',adjustType:'dec',qty:3}),/庫存不足/);assert.equal(S.all().services[1].stock,2);await assert.rejects(S.inventory({id:'p',action:'restock',qty:1.5,cost:20}),/整數/);console.log('PASS inventory validation and linked expense');
 const pending=await S.savePending({cart:f.input().items,draftId:'draft-a'},'waiting');S.draftSave({cart:f.input().items,pendingId:pending.id});assert.equal(S.backupPayload().pendingOrders.length,1);assert.equal(S.backupPayload().draft.pendingId,pending.id);await S.checkout({...f.input(),pendingId:pending.id});assert.equal(S.all().pendingOrders.length,0);assert.equal(S.draftRead(),null);console.log('PASS complete backup and checkout removes only completed pending order');
 assert.equal(S.day('2026-09-30T23:30:00Z'),'2026-10-01');assert.equal(S.itemCost({cost:300},1800),300);assert.equal(S.itemCost({cost:20,costMode:'percent'},1000),200);await assert.rejects(S.restore({transactions:[]}),/完整/);console.log('PASS Taiwan date, explicit cost units and incomplete backup rejection');
 f=fixture();S=f.store;let remote=null,patches=0;f.ctx.fetch=async(url,opt)=>{if(opt?.method==='PATCH'){patches++;assert.ok(url.includes('currentDocument.'));remote={...JSON.parse(opt.body),updateTime:'2026-10-03T01:00:00Z'};return {ok:true,status:200,json:async()=>remote};}return {ok:!!remote,status:remote?200:404,json:async()=>remote};};await S.cloudBackup(S.all().settings,true);assert.equal(patches,1);assert.equal(S.cloudSnapshot().state,'saved');remote.updateTime='2026-10-03T02:00:00Z';await assert.rejects(S.cloudBackup(S.all().settings,true),/其他裝置/);assert.equal(patches,1);assert.equal(S.all().transactions.length,0);console.log('PASS cloud readback confirmation and concurrent-device overwrite protection');
 // Exercise real compression on data larger than Firestore's entire document limit.
 f=fixture();S=f.store;remote=null;patches=0;let corruptRead=false,verifyNext=false;
 f.ctx.fetch=async(url,opt)=>{if(opt?.method==='PATCH'){patches++;verifyNext=true;remote={...JSON.parse(opt.body),updateTime:'revision-'+patches};return {ok:true,status:200,json:async()=>remote};}const bad=verifyNext&&corruptRead;verifyNext=false;return {ok:!!remote,status:remote?200:404,json:async()=>bad?{...remote,fields:{content:{stringValue:'{}'}}}:remote};};
 const large=Array.from({length:8000},(_,i)=>({id:'order-'+i,customerId:'c',date:'2026-10-03T10:00',items:[{name:'剪髮／染髮／護髮 ✂️',stylistId:'s1',price:1800}],total:1800,note:'測試完整備份，不得遺漏掛單與顧客資料'}));f.set('salon_transactions',large);S.draftSave({cart:[{name:'尚未結帳'}]});
 const expected=JSON.stringify(S.all().transactions);assert.ok(new TextEncoder().encode(JSON.stringify(S.backupPayload())).length>1048576);
 await S.cloudBackup(S.all().settings,true);assert.equal(patches,1);assert.equal(S.cloudSnapshot().state,'saved');const envelope=JSON.parse(remote.fields.content.stringValue);assert.equal(envelope.format,'salon-pos-gzip-v1');assert.ok(remote.fields.content.stringValue.length<900000);
 let downloaded=await S.cloudDownload(S.all().settings);assert.equal(JSON.stringify(downloaded.transactions),expected);assert.equal(downloaded.draft.cart[0].name,'尚未結帳');console.log('PASS >1 MiB multilingual backup compresses, reads back and restores every record');
 // Modern native compression interoperates with the bundled legacy-browser decoder.
 f.ctx.CompressionStream=CompressionStream;f.ctx.Blob=Blob;f.ctx.Response=Response;await S.cloudBackup(S.all().settings,true);downloaded=await S.cloudDownload(S.all().settings);assert.equal(JSON.stringify(downloaded.transactions),expected);console.log('PASS native and fallback gzip produce readable backups');
 const intact=remote.fields.content.stringValue;remote.fields.content.stringValue=JSON.stringify({...JSON.parse(intact),sha256:'0'.repeat(64)});await assert.rejects(S.cloudDownload(S.all().settings),/完整性/);assert.equal(JSON.stringify(S.all().transactions),expected);console.log('PASS corrupt compressed backup never changes local orders');remote.fields.content.stringValue=intact;
 corruptRead=true;await assert.rejects(S.cloudBackup(S.all().settings,true),/讀回/);assert.equal(S.cloudSnapshot().state,'error');console.log('PASS successful PATCH alone cannot report backup success');await assert.rejects(S.cloudBackup(S.all().settings),/手動/);corruptRead=false;await S.cloudBackup(S.all().settings,true);assert.equal(S.cloudSnapshot().state,'saved');console.log('PASS failed readback requires manual retry and permits safe recovery');
 // Incompressible oversized backup must stop before writing, preserving prior remote data.
 f=fixture();S=f.store;patches=0;f.ctx.fetch=async(url,opt)=>{if(opt?.method==='PATCH')patches++;return {ok:false,status:404,json:async()=>({})};};const random=require('node:crypto').randomBytes(1000000).toString('base64');f.set('salon_transactions',[{id:'random',note:random}]);await assert.rejects(S.cloudBackup(S.all().settings,true),/壓縮後仍有/);assert.equal(patches,0);assert.equal(S.all().transactions[0].note,random);console.log('PASS oversize compressed backup preserves local data without cloud write');
 // Local quota regression: old plain data + snapshot consume almost all storage.
 f=fixture();S=f.store;f.set('salon_transactions',large);f.set(S.PREFIX+'before-restore',S.backupPayload());f.data.set('other-app','preserve me');const used=()=>[...f.data].reduce((n,[k,v])=>n+k.length+v.length,0);const previousUsage=used();f.quota(previousUsage+1000);
 const incoming={...S.backupPayload(),transactions:large.map(t=>({...t,id:'new-'+t.id})),settings:{...S.all().settings,autoCloudBackup:true},pendingOrders:[{id:'pending-test'}],draft:{cart:[{name:'護髮'}]}};
 // Reproduce the previous implementation's failure without touching real data.
 assert.throws(()=>f.ctx.localStorage.setItem('legacy-journal',JSON.stringify({after:incoming})),/quota/);
 await S.restore(incoming);assert.equal(S.all().transactions.length,8000);assert.equal(S.all().transactions[0].id,'new-order-0');assert.equal(S.read(S.PREFIX+'before-restore').transactions[0].id,'order-0');assert.equal(S.all().pendingOrders[0].id,'pending-test');assert.equal(S.draftRead().cart[0].name,'護髮');assert.equal(S.all().settings.autoCloudBackup,false);assert.equal(f.data.get('other-app'),'preserve me');assert.ok(used()<previousUsage/3);
 vm.runInNewContext(fs.readFileSync(path.join(root,'self-pos-runtime.js'),'utf8'),f.ctx);S=f.ctx.SalonStore;assert.equal(S.all().transactions.length,8000);assert.equal(f.ctx.AetherPosBridge.read('salon_transactions',[]).length,8000);console.log('PASS quota-constrained restore, old snapshot, draft, pending and reload; unrelated storage untouched');
 f=fixture();S=f.store;const before=JSON.stringify(S.all());f.quota(10000);await assert.rejects(S.restore({...S.backupPayload(),transactions:[{id:'large',note:random}]}),/尚未開始/);assert.equal(JSON.stringify(S.all()),before);assert.equal(f.data.has(f.ctx.AetherPosBridge.PREFIX+'journal'),false);assert.equal(f.data.has(S.PREFIX+'before-restore'),false);console.log('PASS insufficient capacity rejects before restoring any records or snapshot');
 f=fixture();S=f.store;f.fail('salon_transactions');await assert.rejects(S.restore({...S.backupPayload(),transactions:large}),/儲存未完成/);assert.ok(f.data.get(f.ctx.AetherPosBridge.PREFIX+'journal').startsWith('salon-local-gzip-v1:'));f.ctx.AetherPosBridge.recover();assert.equal(S.all().transactions.length,8000);assert.equal(S.read(S.PREFIX+'before-restore').transactions.length,0);console.log('PASS interrupted compressed restore recovers all records and original snapshot');
 // Protection runs even on a new phone without any upload receipt.
 f=fixture();S=f.store;const cloudPayload={...S.backupPayload(),transactions:[{id:'original',total:600}],customers:[...S.all().customers,{id:'cloud-c',name:'雲端顧客'}]};remote={fields:{content:{stringValue:JSON.stringify(cloudPayload)}},updateTime:'cloud-1'};patches=0;
 f.ctx.fetch=async(url,opt)=>{if(opt?.method==='PATCH'){patches++;remote={...JSON.parse(opt.body),updateTime:'cloud-'+(patches+1)};}return {ok:true,status:200,json:async()=>remote};};
 await assert.rejects(S.cloudBackup(S.all().settings,true),/防誤覆蓋.*訂單/);assert.equal(patches,0);
 f.set('salon_transactions',[{id:'different-a'},{id:'different-b'}]);await assert.rejects(S.cloudBackup(S.all().settings,true),/缺少.*訂單/);assert.equal(patches,0);
 f.set('salon_transactions',cloudPayload.transactions);await assert.rejects(S.cloudBackup(S.all().settings,true),/防誤覆蓋.*顧客/);assert.equal(patches,0);
 const restored=await S.cloudDownload(S.all().settings);await S.restore(restored);await S.cloudBackup(S.all().settings,true);assert.equal(patches,1);f.set('salon_transactions',[...cloudPayload.transactions,{id:'additional',total:100}]);await S.cloudBackup(S.all().settings);assert.equal(patches,2);
 f.set('salon_transactions',[]);await assert.rejects(S.cloudBackup(S.all().settings),/防誤覆蓋/);assert.equal(patches,2);console.log('PASS new-phone/manual/automatic overwrite guard; equal complete or larger complete data allowed');
 remote.updateTime='other-device';await assert.rejects(S.cloudBackup(S.all().settings,true),/其他裝置/);const latest=await S.cloudDownload(S.all().settings);await S.restore(latest);await S.cloudBackup(S.all().settings,true);assert.equal(patches,3);console.log('PASS successful restore adopts downloaded version while retaining subsequent conflict protection');
})().catch(e=>{console.error(e);process.exitCode=1});
